import { Vector3 } from '@babylonjs/core'

const flappyBird = {
  id: 'flappy_bird',
  name: 'flappy_bird',
  mechanism: 'flappy_bird',
  lives: 1,
  assets: {
    models: {
      player: 'yellowbird-downflap.png',
      box1: 'pipe-green.png',
      box2: 'pipe-green.png',
      score: '',
      player_jump: 'yellowbird-upflap.png',
    },
    sounds: {
      jump: { file: 'wing.wav', volume: 1 },
      collision_player_box2: { file: 'hit.wav', volume: 1 },
      collision_player_box1: { file: 'hit.wav', volume: 1 },
      collision_player_score: { file: 'point.wav', volume: 1 },
    },
    skybox: 'flappybird_bg.png',
    ground: '',
  },
  player: {
    size: 20,
    jumpPower: 45,
    moveSpeed: 30,
    description: 'a bird',
    friction: 0,
    mass: 100,
    restitution: 0.4,
    jumpAnimationDuration: 200,
    jumpSquishScale: 0.9,
    jumpStretchScale: 1.2,
    jumpOnlyOnGround: false,
    walkingStyle: 'normal',
    jumpingStyle: 'rotate',
    initialRotation: [0, 0, -Math.PI / 8],
    bullets: {
      speed: 0.6, maxCount: 40, cooldown: 120,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 110, color: { r: 0.2, g: 0.8, b: 0.3 }, opacity: 0.9,
    },
    startPosition: { x: 0, y: 4, z: -15 },
    lockXPosition: true,
  },
  controls: {
    moveLeft: [''], moveRight: [''], jump: [' '],
    squeezeToJump: [''], fireBullet: [''], bulletLeft: [''], bulletRight: [''],
  },
  world: {
    gravityMultiplier: 1.8,
    description: 'the sky',
    hasGround: false,
    cameraType: 'ortho',
    orthoHeight: 200,
    orthoWidth: 250,
    cameraFovScale: 1,
    cameraTargetDelta: [0, 0, 0],
    cameraAlphaDelta: 0,
    cameraBetaDelta: 0,
    cameraRadiusDelta: 0,
    HemisphericLight: { intensity: 1.6, color: [1, 1, 0.9], direction: [1, 0.5, 0.2] },
    DirectionalLight: { intensity: 0.4, color: [0.9, 1, 1], direction: [-1.4, -0.85, 1] },
    BottomLight: { intensity: 0.1, color: [1, 0.9, 0.9], direction: [1, 0.2, 0] },
    ground: { posY: -35 },
    skyboxType: 'box',
    particles: {
      maxStars: 100, ratioOfBlinkers: 0.4,
      size: { min: 0.2, max: 1.2 }, colors: [[1, 1, 1, 0.8]],
      movement: { pattern: 'scroll', direction: 'left', speed: 0.6, oscillation: { amplitude: 1.5, frequency: 0.05 } },
      blinking: { minInterval: 800, maxInterval: 2000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: true, color: [0, 0.25, 0.5], start: 200, end: 1200, mode: 'linear' },
  },
  objects: [
    {
      name: 'tube', id: 'box1',
      size: new Vector3(20, 100, 10),
      onPlayerCollision: { player: 'die', object: 'none' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(-30, 0, 0),
      motionType: 1,
      initialRotation: new Vector3(0, 0, Math.PI),
    },
    {
      name: 'tube', id: 'box2',
      size: new Vector3(20, 100, 10),
      onPlayerCollision: { player: 'die', object: 'none' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(-30, 0, 0),
      motionType: 1,
    },
    {
      name: 'score', id: 'score',
      size: new Vector3(10, 0.1, 0.1),
      onPlayerCollision: { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(-30, 0, 0),
      motionType: 1,
      isTrigger: true,
      score: 1,
    },
  ],
  spawn: [{
    spawnTrigger: 'timer',
    spawnTriggerTime: 2000,
    spawnXrange: [120, 120], spawnZrange: [-15, -15],
    spawnYrange: [40, 55],
    spawnOffset: {
      box1: new Vector3(0, 40, 0),
      box2: new Vector3(0, -100, 0),
      score: new Vector3(0, -30, 0),
    },
    spawnLikelihood: { box1: 1, box2: 1, score: 1 },
    scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [3, 3],
  }],
}

const persimmonCatch = {
  id: 'cr_persimon',
  name: 'Persimmon Catch',
  mechanism: 'dodge_and_catch',
  assets: {
    models: {
      player: 'bear1.png',
      box1: 'persimon.png',
      box2: 'persimon.png',
      box3: '',
      player_jump: 'bear2.png',
    },
    sounds: {
      ambient: { file: 'test_audio.mp3', volume: 0.1, loop: true },
      jump: { file: 'jump_sound.mp3' },
      collision_player_box2: { file: 'catch_gift_sound2.wav' },
      collision_player_box1: { file: 'catch_gift_sound2.wav' },
    },
    skybox: 'bg_apple.png',
    ground: 'bear_grass.png',
  },
  player: {
    description: 'a cute bear',
    size: 30,
    jumpPower: 45,
    moveSpeed: 30,
    friction: 7,
    mass: 10,
    restitution: 0.4,
    jumpAnimationDuration: 500,
    jumpSquishScale: 1,
    jumpStretchScale: 1.05,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed: 0.6, maxCount: 1, cooldown: 1000,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 110, color: { r: 0.2, g: 0.8, b: 0.3 }, opacity: 0.9,
    },
    startPosition: { x: 0, y: 0, z: 70 },
  },
  controls: {
    moveLeft: ['arrowleft'],
    moveRight: ['arrowright'],
    jump: ['arrowup', ''],
    squeezeToJump: [' '],
    fireBullet: [''],
    bulletLeft: [''],
    bulletRight: [''],
  },
  world: {
    description: 'orchard',
    gravityMultiplier: 1.3,
    hasGround: true,
    ground: { width: 400, height: 10, depth: 400, posY: -40 },
    cameraType: 'normal',
    cameraFovScale: 1,
    cameraTargetDelta: [0, 7, 0],
    cameraAlphaDelta: 0,
    cameraBetaDelta: 13,
    cameraRadiusDelta: -100,
    HemisphericLight: { intensity: 2.6, color: [1, 1, 1], direction: [0, 0.3, 0.2] },
    DirectionalLight: { intensity: 0.4, color: [0.9, 0.9, 0.9], direction: [0, -0.85, 1] },
    BottomLight: { intensity: 0.1, color: [0.9, 0.9, 0.9], direction: [0, 1, 0] },
    skyboxType: 'box',
    particles: {
      maxStars: 80, ratioOfBlinkers: 0.4,
      size: { min: 0.1, max: 0.7 }, colors: [[1, 1, 1, 0.8]],
      movement: { pattern: 'oscillate', direction: 'down', speed: 0.6, oscillation: { amplitude: 1, frequency: 0.05 } },
      blinking: { minInterval: 800, maxInterval: 2000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: false, color: [0.1, 0.1, 0.1], start: 0, end: 800, mode: 'linear' },
  },
  objects: [
    {
      name: 'persimons', id: 'box1',
      size: new Vector3(5, 5, 5),
      onPlayerCollision: { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'score', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: new Vector3(0, -10, 0),
      motionType: 2,
    },
    {
      name: 'persimons', id: 'box2',
      size: new Vector3(10, 10, 10),
      onPlayerCollision: { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'none', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: new Vector3(0, -10, 0),
      score: 10,
      motionType: 2,
    },
  ],
  spawn: [
    {
      spawnTrigger: 'timer',
      spawnTriggerTime: 1200,
      spawnXrange: [-200, 200],
      spawnZrange: [70, 70],
      spawnYrange: [10, 30],
      spawnLikelihood: { box1: 0.8 },
      uniformScaleRange: [0.9, 0.9],
    },
    {
      spawnTrigger: 'timer',
      spawnTriggerTime: 1000,
      spawnXrange: [-80, 80],
      spawnZrange: [70, 70],
      spawnYrange: [10, 30],
      spawnLikelihood: { box2: 0.8 },
      uniformScaleRange: [0.9, 0.9],
    },
  ],
}

const GAMES = [
  {
    id: 'flappy',
    name: 'Flappy Bird',
    creator: '@smallGami',
    skybox: 'flappybird_bg.png',
    config: flappyBird,
  },
  {
    id: 'persimmon',
    name: 'Persimmon Catch',
    creator: '@smallGami',
    skybox: 'bg_apple.png',
    config: persimmonCatch,
  },
]

export default GAMES
