import type { GameDSLConfig } from '@smallgami/engine';

// Normal camera arc-catch — fruits launch from both sides and arc through the
// air; move the ninja to slice them before they hit the ground.
const fruitNinja: GameDSLConfig = {
  id: 'fruit_ninja',
  name: 'Fruit Ninja',
  mechanism: 'dodge_and_catch',
  assets: {
    models: { player: '', fruit_l: '', fruit_r: '', bomb: '' },
    sounds: {
      ambient:                  { file: 'test_audio.mp3', volume: 0.06, loop: true },
      jump:                     { file: 'jump_sound.mp3' },
      collision_player_fruit_l: { file: 'catch_gift_sound2.wav' },
      collision_player_fruit_r: { file: 'catch_gift_sound2.wav' },
      collision_player_bomb:    { file: 'ouch_sound.wav' },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'a swift shadow ninja',
    size: 5,
    jumpPower: 62,
    moveSpeed: 48,
    friction: 6,
    mass: 8,
    restitution: 0.1,
    jumpAnimationDuration: 320,
    jumpSquishScale: 0.88,
    jumpStretchScale: 1.18,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: 0, y: -8, z: 0 },
  },
  controls: {
    moveLeft:     ['arrowleft',  'a'],
    moveRight:    ['arrowright', 'd'],
    jump:         ['arrowup',    ' '],
    squeezeToJump: [''],
    fireBullet:   [''],
    bulletLeft:   [''],
    bulletRight:  [''],
  },
  world: {
    description: 'a dojo at sunset — fruits fly, the blade never rests',
    gravityMultiplier: 0.85,
    hasGround: true,
    ground: { width: 400, height: 1, depth: 10, posY: -20 },
    cameraType: 'normal',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 6, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    18,
    cameraRadiusDelta: -22,
    HemisphericLight: { intensity: 0.50, color: [1.0, 0.85, 0.65], direction: [0,  0.3, 0.2] },
    DirectionalLight: { intensity: 0.55, color: [1.0, 0.80, 0.50], direction: [0.6, -0.8, 0.4] },
    BottomLight:      { intensity: 0.15, color: [0.9, 0.75, 0.55], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 40,
      ratioOfBlinkers: 0.45,
      size: { min: 0.2, max: 0.5 },
      colors: [[1, 0.7, 0.3, 0.4]],
      movement: {
        pattern: 'drift',
        direction: 'down',
        speed: 0.06,
        oscillation: { amplitude: 0.8, frequency: 0.04 },
      },
      blinking: { minInterval: 800, maxInterval: 2500 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: true, color: [0.6, 0.4, 0.2], start: 350, end: 900, mode: 'linear' },
  },
  objects: [
    {
      // Fruit launched from the left — arcs right and upward then falls
      name: 'fruit (left)',
      id: 'fruit_l',
      size: { x: 5, y: 5, z: 5 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: 88, y: 38, z: 0 } as any,
      score: 10,
      motionType: 2,
    },
    {
      // Fruit launched from the right — arcs left and upward then falls
      name: 'fruit (right)',
      id: 'fruit_r',
      size: { x: 5, y: 5, z: 5 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: -88, y: 38, z: 0 } as any,
      score: 10,
      motionType: 2,
    },
    {
      // Bomb — drops straight down, avoid it
      name: 'bomb',
      id: 'bomb',
      size: { x: 4, y: 4, z: 4 } as any,
      onPlayerCollision:     { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: 0, y: -28, z: 0 } as any,
      motionType: 2,
    },
  ],
  spawn: [
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 900,
      spawnXrange:  [-200, -200],
      spawnZrange:  [0, 0],
      spawnYrange:  [-8, -8],
      spawnLikelihood: { fruit_l: 0.72 },
      uniformScaleRange: [0.85, 1.25],
    },
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 900,
      spawnXrange:  [200, 200],
      spawnZrange:  [0, 0],
      spawnYrange:  [-8, -8],
      spawnLikelihood: { fruit_r: 0.72 },
      uniformScaleRange: [0.85, 1.25],
    },
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 2500,
      spawnXrange:  [-80, 80],
      spawnZrange:  [0, 0],
      spawnYrange:  [30, 55],
      spawnLikelihood: { bomb: 0.38 },
      uniformScaleRange: [0.9, 1.0],
    },
  ],
};

export default fruitNinja;
