import type { GameDSLConfig } from '@smallgami/engine';

// Pac-Man — navigate a neon maze, gobble every pellet, dodge the ghosts.
const pacman: GameDSLConfig = {
  id: 'pacman',
  name: 'Pac-Man',
  mechanism: 'navigator',
  assets: {
    models: { player: '', pellet: '', ghost: '' },
    sounds: {
      ambient:                  { file: 'test_audio.mp3', volume: 0.05, loop: true },
      jump:                     { file: 'jump_sound.mp3' },
      collision_player_pellet:  { file: 'catch_gift_sound2.wav' },
      collision_player_ghost:   { file: 'ouch_sound.wav' },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'a hungry yellow circle chomping through a maze',
    size: 5,
    jumpPower: 0,
    moveSpeed: 35,
    friction: 8,
    mass: 10,
    restitution: 0,
    jumpAnimationDuration: 300,
    jumpSquishScale: 1,
    jumpStretchScale: 1,
    jumpOnlyOnGround: true,
    maxJumpCount: 0,
    jumpInterval: 500,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: 0, y: 0, z: 0 },
  },
  controls: {
    moveLeft:      ['arrowleft',  'a'],
    moveRight:     ['arrowright', 'd'],
    moveforward:   ['arrowup',   'w'],
    movebackward:  ['arrowdown', 's'],
    jump:          [''],
    squeezeToJump: [''],
    fireBullet:    [''],
    bulletLeft:    [''],
    bulletRight:   [''],
  },
  world: {
    description: 'a dark neon maze — corridors glow as pellets wait to be eaten',
    gravityMultiplier: 0,
    hasGround: true,
    ground: { width: 400, height: 1, depth: 400, posY: -5 },
    cameraType: 'ortho',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 0, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    0,
    cameraRadiusDelta:  0,
    HemisphericLight: { intensity: 0.4, color: [0.7, 0.7, 1.0], direction: [0, 1, 0] },
    DirectionalLight: { intensity: 0.3, color: [0.5, 0.5, 1.0], direction: [0, -1, 0.5] },
    BottomLight:      { intensity: 0.2, color: [0.3, 0.3, 0.8], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 18,
      ratioOfBlinkers: 0.6,
      size: { min: 0.15, max: 0.35 },
      colors: [[1, 1, 0.3, 0.25], [0.3, 0.5, 1, 0.2]],
      movement: {
        pattern: 'drift',
        direction: 'up',
        speed: 0.02,
        oscillation: { amplitude: 0.3, frequency: 0.02 },
      },
      blinking: { minInterval: 600, maxInterval: 2000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: true, color: [0.05, 0.05, 0.15], start: 150, end: 600, mode: 'linear' },
  },
  objects: [
    {
      name: 'pellet',
      id: 'pellet',
      size: { x: 2, y: 2, z: 2 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'none', projectile: 'none' },
      onGroundCollision: 'none',
      initialSpeed: { x: 0, y: 0, z: 0 } as any,
      score: 10,
      motionType: 0,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
    {
      name: 'ghost',
      id: 'ghost',
      size: { x: 5, y: 5, z: 5 } as any,
      onPlayerCollision:     { player: 'none', object: 'none' },
      onProjectileCollision: { object: 'none', projectile: 'none' },
      onGroundCollision: 'none',
      initialSpeed: { x: 14, y: 0, z: 10 } as any,
      motionType: 1,
      physics: { mass: 0, restitution: 1, friction: 0 },
    },
  ],
  spawn: [
    // Pellets scattered across the maze
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    // Pellet respawn
    { spawnTrigger: 'timer', spawnTriggerTime: 4000, spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { pellet: 0.8 }, scaleRangeX: [0.8, 1.2], scaleRangeY: [0.8, 1.2], scaleRangeZ: [0.8, 1.2] },
    // Ghosts
    { spawnTrigger: 'once', spawnTriggerTime: 500,  spawnXrange: [-28, -28], spawnZrange: [-10, 10], spawnYrange: [0, 0], spawnLikelihood: { ghost: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 500,  spawnXrange: [28, 28],   spawnZrange: [-10, 10], spawnYrange: [0, 0], spawnLikelihood: { ghost: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 1500, spawnXrange: [-10, 10],  spawnZrange: [28, 28],  spawnYrange: [0, 0], spawnLikelihood: { ghost: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 2500, spawnXrange: [-10, 10],  spawnZrange: [-28, -28], spawnYrange: [0, 0], spawnLikelihood: { ghost: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
  ],
};

export default pacman;
