import type { GameDSLConfig } from '@smallgami/engine';

// Ortho camera side-scroller — Kiko the fox dashes through ancient ruins,
// leaping over stone spikes and snatching golden coins.
const platform: GameDSLConfig = {
  id: 'pl_ruins',
  name: "Kiko's Journey",
  mechanism: 'platformer',
  assets: {
    models: { player: '', spike: '', coin: '' },
    sounds: {
      ambient:                  { file: 'test_audio.mp3', volume: 0.08, loop: true },
      jump:                     { file: 'jump_sound.mp3' },
      collision_player_coin:    { file: 'catch_gift_sound2.wav' },
      collision_player_spike:   { file: 'ouch_sound.wav' },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'Kiko the fox, a nimble explorer of forgotten ruins',
    size: 5,
    jumpPower: 80,
    moveSpeed: 55,
    friction: 8,
    mass: 8,
    restitution: 0.05,
    jumpAnimationDuration: 350,
    jumpSquishScale: 0.85,
    jumpStretchScale: 1.2,
    jumpOnlyOnGround: true,
    maxJumpCount: 1,
    jumpInterval: 300,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: -120, y: -5, z: 0 },
  },
  controls: {
    moveLeft:    ['arrowleft',  'a'],
    moveRight:   ['arrowright', 'd'],
    jump:        ['arrowup',    ' '],
    squeezeToJump: [''],
    fireBullet:  [''],
    bulletLeft:  [''],
    bulletRight: [''],
  },
  world: {
    description: 'ancient crumbling ruins bathed in golden dusk light',
    gravityMultiplier: 2,
    hasGround: true,
    ground: { width: 1000, height: 1, depth: 10, posY: -18 },
    cameraType: 'ortho',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 5, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    0,
    cameraRadiusDelta: -20,
    HemisphericLight:  { intensity: 0.5, color: [0.95, 0.88, 0.70], direction: [0,  0.3, 0.2] },
    DirectionalLight:  { intensity: 0.6, color: [1.00, 0.92, 0.75], direction: [0.4, -0.85, 0.3] },
    BottomLight:       { intensity: 0.15, color: [0.8, 0.70, 0.50], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 25,
      ratioOfBlinkers: 0.3,
      size: { min: 0.2, max: 0.4 },
      colors: [[1, 0.9, 0.6, 0.35]],
      movement: {
        pattern: 'drift',
        direction: 'down',
        speed: 0.04,
        oscillation: { amplitude: 0.5, frequency: 0.03 },
      },
      blinking: { minInterval: 1200, maxInterval: 3500 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: true, color: [0.55, 0.42, 0.28], start: 300, end: 900, mode: 'linear' },
  },
  objects: [
    {
      name: 'stone spike',
      id: 'spike',
      size: { x: 5, y: 10, z: 5 } as any,
      onPlayerCollision:     { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: { x: -85, y: 0, z: 0 } as any,
      motionType: 1,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
    {
      name: 'gold coin',
      id: 'coin',
      size: { x: 3, y: 3, z: 3 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: { x: -85, y: 0, z: 0 } as any,
      score: 10,
      motionType: 1,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
  ],
  spawn: [
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 1400,
      spawnXrange:  [200, 200],
      spawnZrange:  [0,   0],
      spawnYrange:  [-15, -15],
      spawnLikelihood: { spike: 0.65 },
      uniformScaleRange: [0.9, 1.3],
    },
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 900,
      spawnXrange:  [180, 200],
      spawnZrange:  [0,   0],
      spawnYrange:  [2,   14],
      spawnLikelihood: { coin: 0.55 },
      uniformScaleRange: [0.8, 1.0],
    },
  ],
};

export default platform;
