import type { GameDSLConfig } from '@smallgami/engine';

// Normal camera vertical platformer — jump upward landing on rising platforms,
// don't fall below. Classic Doodle Jump feel.
const doodleJump: GameDSLConfig = {
  id: 'doodle_jump',
  name: 'Doodle Jump',
  mechanism: 'platformer',
  assets: {
    models: { player: '', platform: '', monster: '' },
    sounds: {
      ambient:                   { file: 'test_audio.mp3', volume: 0.08, loop: true },
      jump:                      { file: 'jump_sound.mp3' },
      collision_player_monster:  { file: 'ouch_sound.wav' },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'the Doodle — a spring-legged creature bouncing endlessly upward',
    size: 4,
    jumpPower: 90,
    moveSpeed: 55,
    friction: 4,
    mass: 5,
    restitution: 0.05,
    jumpAnimationDuration: 220,
    jumpSquishScale: 0.80,
    jumpStretchScale: 1.30,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 150,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: 0, y: -5, z: 0 },
  },
  controls: {
    moveLeft:     ['arrowleft',  'a'],
    moveRight:    ['arrowright', 'd'],
    jump:         ['arrowup',    ' '],
    squeezeToJump: [''],
    fireBullet:   [''],
    bulletLeft:   [''],
    bulletRight:  [''],
  },
  world: {
    description: 'a pastel-coloured infinite sky full of bouncy platforms',
    gravityMultiplier: 1.4,
    hasGround: false,
    ground: { width: 400, height: 1, depth: 10, posY: -60 },
    cameraType: 'normal',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 8, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    10,
    cameraRadiusDelta: -25,
    HemisphericLight: { intensity: 0.55, color: [0.95, 0.98, 1.0],  direction: [0,  0.3, 0.2] },
    DirectionalLight: { intensity: 0.50, color: [1.00, 0.95, 0.90], direction: [0.3, -0.85, 0.4] },
    BottomLight:      { intensity: 0.20, color: [0.80, 0.95, 0.85], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 60,
      ratioOfBlinkers: 0.5,
      size: { min: 0.15, max: 0.45 },
      colors: [[0.6, 1, 0.75, 0.5]],
      movement: {
        pattern: 'drift',
        direction: 'down',
        speed: 0.08,
        oscillation: { amplitude: 1.0, frequency: 0.04 },
      },
      blinking: { minInterval: 600, maxInterval: 2000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: false, color: [0.8, 0.95, 0.85], start: 400, end: 1000, mode: 'linear' },
  },
  objects: [
    {
      name: 'platform',
      id: 'platform',
      size: { x: 18, y: 2, z: 8 } as any,
      onPlayerCollision:     { player: 'none', object: 'none' },
      onProjectileCollision: { object: 'none', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: { x: 0, y: -10, z: 0 } as any,
      motionType: 1,
      physics: { mass: 0, restitution: 0.5, friction: 1 },
    },
    {
      name: 'monster',
      id: 'monster',
      size: { x: 6, y: 6, z: 6 } as any,
      onPlayerCollision:     { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: { x: 0, y: -10, z: 0 } as any,
      motionType: 1,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
  ],
  spawn: [
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 700,
      spawnXrange:  [-90, 90],
      spawnZrange:  [0,   0],
      spawnYrange:  [50,  90],
      spawnLikelihood: { platform: 0.85 },
      uniformScaleRange: [0.8, 1.4],
    },
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 3000,
      spawnXrange:  [-60, 60],
      spawnZrange:  [0,   0],
      spawnYrange:  [70, 100],
      spawnLikelihood: { monster: 0.4 },
      uniformScaleRange: [0.9, 1.1],
    },
  ],
};

export default doodleJump;
