import type { GameDSLConfig } from '@smallgami/engine';

// Classic Snake — slither across a grassy field, eat apples, avoid the growing
// obstacle trail.  The arena slowly fills with walls as time passes.
const snake: GameDSLConfig = {
  id: 'snake',
  name: 'Snake',
  mechanism: 'navigator',
  assets: {
    models: { player: '', apple: '', obstacle: '' },
    sounds: {
      ambient:                   { file: 'test_audio.mp3', volume: 0.04, loop: true },
      jump:                      { file: 'jump_sound.mp3' },
      collision_player_apple:    { file: 'catch_gift_sound2.wav' },
      collision_player_obstacle: { file: 'ouch_sound.wav' },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'a green snake slithering across the field',
    size: 4,
    jumpPower: 0,
    moveSpeed: 30,
    friction: 10,
    mass: 10,
    restitution: 0,
    jumpAnimationDuration: 300,
    jumpSquishScale: 1,
    jumpStretchScale: 1,
    jumpOnlyOnGround: true,
    maxJumpCount: 0,
    jumpInterval: 500,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: 0, y: 0, z: 0 },
  },
  controls: {
    moveLeft:      ['arrowleft',  'a'],
    moveRight:     ['arrowright', 'd'],
    moveforward:   ['arrowup',   'w'],
    movebackward:  ['arrowdown', 's'],
    jump:          [''],
    squeezeToJump: [''],
    fireBullet:    [''],
    bulletLeft:    [''],
    bulletRight:   [''],
  },
  world: {
    description: 'a sun-dappled grassy field — eat the apples, dodge the rocks',
    gravityMultiplier: 0,
    hasGround: true,
    ground: { width: 400, height: 1, depth: 400, posY: -5 },
    cameraType: 'ortho',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 0, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    0,
    cameraRadiusDelta:  0,
    HemisphericLight: { intensity: 0.65, color: [1.0, 1.0, 0.9], direction: [0, 1, 0] },
    DirectionalLight: { intensity: 0.45, color: [1.0, 0.95, 0.7], direction: [0.2, -0.9, 0.3] },
    BottomLight:      { intensity: 0.15, color: [0.5, 0.8, 0.3], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 12,
      ratioOfBlinkers: 0.4,
      size: { min: 0.2, max: 0.5 },
      colors: [[0.4, 0.9, 0.2, 0.2], [0.9, 0.8, 0.1, 0.15]],
      movement: {
        pattern: 'drift',
        direction: 'up',
        speed: 0.03,
        oscillation: { amplitude: 0.6, frequency: 0.03 },
      },
      blinking: { minInterval: 1000, maxInterval: 3000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: true, color: [0.45, 0.6, 0.25], start: 200, end: 700, mode: 'linear' },
  },
  objects: [
    {
      name: 'apple',
      id: 'apple',
      size: { x: 3, y: 3, z: 3 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'none', projectile: 'none' },
      onGroundCollision: 'none',
      initialSpeed: { x: 0, y: 0, z: 0 } as any,
      score: 10,
      motionType: 0,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
    {
      name: 'obstacle',
      id: 'obstacle',
      size: { x: 4, y: 4, z: 4 } as any,
      onPlayerCollision:     { player: 'none', object: 'none' },
      onProjectileCollision: { object: 'none', projectile: 'none' },
      onGroundCollision: 'none',
      initialSpeed: { x: 0, y: 0, z: 0 } as any,
      motionType: 0,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
  ],
  spawn: [
    // Initial apples
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-20, 20], spawnZrange: [-20, 20], spawnYrange: [0, 0], spawnLikelihood: { apple: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-20, 20], spawnZrange: [-20, 20], spawnYrange: [0, 0], spawnLikelihood: { apple: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    { spawnTrigger: 'once', spawnTriggerTime: 100,  spawnXrange: [-20, 20], spawnZrange: [-20, 20], spawnYrange: [0, 0], spawnLikelihood: { apple: 1 }, scaleRangeX: [1, 1], scaleRangeY: [1, 1], scaleRangeZ: [1, 1] },
    // Apple respawn
    { spawnTrigger: 'timer', spawnTriggerTime: 3000, spawnXrange: [-22, 22], spawnZrange: [-22, 22], spawnYrange: [0, 0], spawnLikelihood: { apple: 0.9 }, scaleRangeX: [0.8, 1.1], scaleRangeY: [0.8, 1.1], scaleRangeZ: [0.8, 1.1] },
    // Obstacles accumulate over time
    { spawnTrigger: 'timer', spawnTriggerTime: 5000, spawnXrange: [-25, 25], spawnZrange: [-25, 25], spawnYrange: [0, 0], spawnLikelihood: { obstacle: 0.6 }, scaleRangeX: [1, 2], scaleRangeY: [1, 1], scaleRangeZ: [1, 2] },
  ],
};

export default snake;
