import type { GameDSLConfig } from '@smallgami/engine';

// Primitive (polygon-mode) — dodge and catch simultaneously.
// Hazards scroll in horizontally while collectibles fall from above.
// Player must weave left/right to avoid hazards AND position to catch items.
const primDodgeCatch: GameDSLConfig = {
  id: 'prim_dodge_catch',
  name: 'dodge_and_catch',
  mechanism: 'dodge_and_catch',
  assets: { models: { player: '', hazard: '', collectible: '' }, skybox: '', ground: '' },
  player: {
    description: 'player',
    size: 5,
    jumpPower: 50,
    moveSpeed: 40,
    friction: 7,
    mass: 10,
    restitution: 0.2,
    jumpAnimationDuration: 400,
    jumpSquishScale: 0.9,
    jumpStretchScale: 1.1,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed: 0,
      maxCount: 0,
      cooldown: 99999,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 0,
      color: { r: 1, g: 1, b: 1 },
      opacity: 0,
    },
    startPosition: { x: 0, y: -8, z: 0 },
  },
  controls: {
    moveLeft:     ['arrowleft',  'a'],
    moveRight:    ['arrowright', 'd'],
    jump:         ['arrowup',    ' '],
    squeezeToJump: [''],
    fireBullet:   [''],
    bulletLeft:   [''],
    bulletRight:  [''],
  },
  world: {
    description: 'primitive dodge-and-catch arena',
    gravityMultiplier: 1.2,
    hasGround: true,
    ground: { width: 400, height: 1, depth: 10, posY: -18 },
    cameraType: 'normal',
    cameraFovScale: 1,
    cameraTargetDelta:  [0, 6, 0],
    cameraAlphaDelta:   0,
    cameraBetaDelta:    20,
    cameraRadiusDelta: -20,
    HemisphericLight: { intensity: 0.5, color: [1, 1, 1],       direction: [0, 0.3, 0.2] },
    DirectionalLight: { intensity: 0.4, color: [0.9, 0.9, 0.9], direction: [0, -0.85, 1] },
    BottomLight:      { intensity: 0.1, color: [0.9, 0.9, 0.9], direction: [0, 1, 0] },
    skyboxType: 'sphere',
    particles: {
      maxStars: 0,
      ratioOfBlinkers: 0,
      size: { min: 0.1, max: 0.3 },
      colors: [[1, 1, 1, 0.3]],
      movement: {
        pattern: 'drift',
        direction: 'down',
        speed: 0.05,
        oscillation: { amplitude: 0.5, frequency: 0.03 },
      },
      blinking: { minInterval: 1000, maxInterval: 3000 },
      texture: { path: '/texture/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: false, color: [0.3, 0.3, 0.3], start: 200, end: 800, mode: 'linear' },
  },
  objects: [
    {
      // Scrolls in horizontally — dodge it
      name: 'hazard',
      id: 'hazard',
      size: { x: 8, y: 14, z: 8 } as any,
      onPlayerCollision:     { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'none',
      initialSpeed: { x: -75, y: 0, z: 0 } as any,
      motionType: 1,
      physics: { mass: 0, restitution: 0, friction: 0 },
    },
    {
      // Falls from above — catch it
      name: 'collectible',
      id: 'collectible',
      size: { x: 4, y: 4, z: 4 } as any,
      onPlayerCollision:     { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'dispose', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: 0, y: -28, z: 0 } as any,
      score: 10,
      motionType: 2,
    },
  ],
  spawn: [
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 1100,
      spawnXrange:  [180, 180],
      spawnZrange:  [0, 0],
      spawnYrange:  [-12, -12],
      spawnLikelihood: { hazard: 0.7 },
      uniformScaleRange: [0.9, 1.3],
    },
    {
      spawnTrigger:     'timer',
      spawnTriggerTime: 600,
      spawnXrange:  [-120, 120],
      spawnZrange:  [0, 0],
      spawnYrange:  [20, 40],
      spawnLikelihood: { collectible: 0.65 },
      uniformScaleRange: [0.85, 1.1],
    },
  ],
};

export default primDodgeCatch;
