import type { GameDSLConfig } from '@smallgami/engine';

// Normal camera catch — persimmons fall from above; player at z=70, spawn at z=70.
const persimon: GameDSLConfig = {
  id: 'cr_persimon',
  name: 'Persimmon Catch',
  mechanism: 'dodge_and_catch',
  assets: {
    models: {
      player: 'bear1.png',
      box1: 'persimon.png',
      box2: 'persimon.png',
      box3: '',
      player_jump: 'bear2.png',
    },
    sounds: {
      ambient: { file: 'test_audio.mp3', volume: 0.1, loop: true },
      jump: { file: 'jump_sound.mp3' },
      collision_player_box2: { file: 'catch_gift_sound2.wav' },
      collision_player_box1: { file: 'catch_gift_sound2.wav' },
    },
    skybox: 'bg_apple.png',
    ground: 'bear_grass.png',
  },
  player: {
    description: 'a cute bear',
    size: 30,
    jumpPower: 45,
    moveSpeed: 30,
    friction: 7,
    mass: 10,
    restitution: 0.4,
    jumpAnimationDuration: 500,
    jumpSquishScale: 1,
    jumpStretchScale: 1.05,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed: 0.6,
      maxCount: 1,
      cooldown: 1000,
      shape: { width: 1, height: 1, depth: 1 },
      maxDistance: 110,
      color: { r: 0.2, g: 0.8, b: 0.3 },
      opacity: 0.9,
    },
    startPosition: { x: 0, y: 0, z: 70 },
  },
  controls: {
    moveLeft: ['arrowleft'],
    moveRight: ['arrowright'],
    jump: ['arrowup', ''],
    squeezeToJump: [' '],
    fireBullet: [''],
    bulletLeft: [''],
    bulletRight: [''],
  },
  world: {
    description: 'orchard',
    gravityMultiplier: 1.3,
    hasGround: true,
    ground: { width: 400, height: 10, depth: 400, posY: -40 },
    cameraType: 'normal',
    cameraFovScale: 1,
    cameraTargetDelta: [0, 7, 0],
    cameraAlphaDelta: 0,
    cameraBetaDelta: 13,
    cameraRadiusDelta: -100,
    HemisphericLight: { intensity: 2.6, color: [1, 1, 1], direction: [0, 0.3, 0.2] },
    DirectionalLight: { intensity: 0.4, color: [0.9, 0.9, 0.9], direction: [0, -0.85, 1] },
    BottomLight: { intensity: 0.1, color: [0.9, 0.9, 0.9], direction: [0, 1, 0] },
    skyboxType: 'box',
    particles: {
      maxStars: 80,
      ratioOfBlinkers: 0.4,
      size: { min: 0.1, max: 0.7 },
      colors: [[1, 1, 1, 0.8]],
      movement: {
        pattern: 'oscillate',
        direction: 'down',
        speed: 0.6,
        oscillation: { amplitude: 1, frequency: 0.05 },
      },
      blinking: { minInterval: 800, maxInterval: 2000 },
      texture: { path: '/assets/images/star.png', dimensions: { width: 128, height: 128 } },
    },
    fog: { enabled: false, color: [0.1, 0.1, 0.1], start: 0, end: 800, mode: 'linear' },
  },
  objects: [
    {
      name: 'persimons',
      id: 'box1',
      size: { x: 5, y: 5, z: 5 } as any,
      onPlayerCollision: { player: 'none', object: 'dispose' },
      onProjectileCollision: { object: 'score', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: 0, y: -10, z: 0 } as any,
      motionType: 2,
    },
    {
      name: 'persimons',
      id: 'box2',
      size: { x: 10, y: 10, z: 10 } as any,
      onPlayerCollision: { player: 'score', object: 'dispose' },
      onProjectileCollision: { object: 'none', projectile: 'dispose' },
      onGroundCollision: 'disappearing',
      initialSpeed: { x: 0, y: -10, z: 0 } as any,
      score: 10,
      motionType: 2,
    },
  ],
  spawn: [
    {
      spawnTrigger: 'timer',
      spawnTriggerTime: 1200,
      spawnXrange: [-200, 200],
      spawnZrange: [70, 70],
      spawnYrange: [10, 30],
      spawnLikelihood: { box1: 0.8 },
      uniformScaleRange: [0.9, 0.9],
    },
    {
      spawnTrigger: 'timer',
      spawnTriggerTime: 1000,
      spawnXrange: [-80, 80],
      spawnZrange: [70, 70],
      spawnYrange: [10, 30],
      spawnLikelihood: { box2: 0.8 },
      uniformScaleRange: [0.9, 0.9],
    },
  ],
};

export default persimon;
