import { GameDSLConfig } from '@smallgami/engine';
import { Vector3 } from '@babylonjs/core';

export const testConfig: GameDSLConfig = {
  id: 'testConfig',
  name: 'Test Config',
  mechanism: 'dodge_and_catch',
  assets: {
    models: {
      player: 'Player_1.glb',
      alien: 'Alien_1.glb',
      alien2: 'Alien_2.glb',
      alien3: 'Alien_3.glb',
      pinecone: '',
      // player_jump: 'bear_jump.png',
    },
    sounds: {
      ambient: {
        file: 'ambient_space_invader2.wav',
        volume: 0.2,
        loop: true,
      },
      fireBullet: {
        file: 'player-bullet-sfx.wav',
      },
      collision_projectile_alien: {
        file: 'alien-explosion-sfx.wav',
      },
       collision_projectile_alien2: {
        file: 'alien-explosion-sfx.wav',
      },
       collision_projectile_alien3: {
        file: 'alien-explosion-sfx.wav',
      },
      tick: {
        file: "alien-move-sfx.wav",
        volume: 0.01,
      }
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'a cute bear',
    size: 1.4,
    jumpPower: 50,
    moveSpeed: 55,
    friction: 100,
    mass: 10,
    restitution: 0.4,
    jumpAnimationDuration: 500,
    jumpSquishScale: 0.9,
    jumpStretchScale: 1.1,
    jumpOnlyOnGround: false,
    walkingStyle: 'rotate',
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed:  6,
      maxCount: 10,
      cooldown: 50,
      shape: {
        width: 1,
        height: 4   ,
        depth: 1,
      },
      maxDistance: 110,
      color: {
        r: 0.2,
        g: 0.8,
        b: 0.3,
      },
      opacity: 0.9,
      offset: { x: 0, y: 20, z: 2 },
    },
    startPosition: {
      x: 0,
      y:-22,
      z: 0,
    },
  },
  controls: {
    moveLeft: ['arrowleft'],
    moveRight: ['arrowright'],
    jump: [],
    squeezeToJump: [''],
    fireBullet: [' '],
    bulletLeft: [''],
    bulletRight: [''],
  },
  world: {
    description: 'test world environment',
    gravityMultiplier: 1,
    hasGround: true,
    ground: {
      width: 400,
      height: 10,
      depth: 400,
      posY: -35,
    },
    cameraType: 'ortho',
    cameraFovScale: 1,
    cameraTargetDelta: [0, 7, 0],
    cameraAlphaDelta: 14,
    cameraBetaDelta:0,
    cameraRadiusDelta: 0,
    HemisphericLight: {
      intensity: 0.6,
      color: [0.3, 0.3, 0.4],
      direction: [1, 1, 1],
    },
    DirectionalLight: {
      intensity: 0.1,
      color: [0.5, 0.5, 0.6],
      direction: [0, -0.5, 0.5],
    },
    BottomLight: {
      intensity: 0.1,
      color: [0.3, 0.3, 0.4],
      direction: [0, -1, 0],
    },
    skyboxType: 'sphere',
    particles: {
      maxStars: 100,
      ratioOfBlinkers: 0.4,
      size: {
        min: 0.3,
        max: 0.8,
      },
      colors: [
        [1, 0.3, 0.3, 0.8],  // Red
        [1, 1, 0.3, 0.8],    // Yellow
        [0.3, 1, 0.3, 0.8],  // Green
        [1, 0.3, 1, 0.8],    // Magenta/Purple
      ],
      movement: {
        pattern: 'float',
        direction: 'down',
        speed: 0.01,
        oscillation: {
          amplitude: 0.5,
          frequency: 0.03,
        },
      },
      blinking: {
        minInterval: 800,
        maxInterval: 2000,
      },
      texture: {
        path: '/texture/star.png',
        dimensions: {
          width: 128,
          height: 128,
        },
      },
    },
    fog: {
      enabled: false,
      color: [0.0, 0.0, 0.1],
      start: 500,
      end: 2000,
      mode: 'linear',
    },
  },
  objects: [
    {
      name: 'alien',
      id: 'alien',
      size: new Vector3(2, 2, 3.5),
      onPlayerCollision: {
        player: "none",
        object: 'dispose',
      },
      onProjectileCollision: {
        object: 'dispose',
        projectile: 'dispose',
      },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(0, -3, 0),
      motionType: 1,
      physics: {
        mass: 0,
        restitution: 0.5,
        friction: 0,
      },
      motionStyle: 'stopMotion',
      stopMotionInterval: 800,
    },
    {
      name: 'alien2',
      id: 'alien2',
      size: new Vector3(2, 2, 3.5),
      onPlayerCollision: {
        player: "none",
        object: 'dispose',
      },
      onProjectileCollision: {
        object: 'dispose',
        projectile: 'dispose',
      },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(0, -3, 0),
      motionType: 1,
      physics: {
        mass: 0,
        restitution: 0.5,
        friction: 0,
      },
      motionStyle: 'stopMotion',
      stopMotionInterval: 800,
    },
    {
      name: 'alien3',
      id: 'alien3',
      size: new Vector3(2, 2, 3.5),
      onPlayerCollision: {
        player: "none",
        object: 'dispose',
      },
      onProjectileCollision: {
        object: 'dispose',
        projectile: 'dispose',
      },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(0, -3, 0),
      motionType: 1,
      physics: {
        mass: 0,
        restitution: 0.5,
        friction: 0,
      },
      motionStyle: 'stopMotion',
      stopMotionInterval: 800,
    },
  ],
  spawn: [
    {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10, -10],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
       {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10, -10],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10,-10],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
       spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
       spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10,-10],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [100, 100],
      spawnLikelihood: {
        alien3: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [100, 100],
      spawnLikelihood: {
        alien3: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
       spawnYrange: [100, 100],
      spawnLikelihood: {
        alien3: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10,-10],
      spawnZrange: [-5, -5],
      spawnYrange: [100, 100],
      spawnLikelihood: {
        alien3: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [100, 100],
      spawnLikelihood: {
        alien3: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
  ],
};

export default testConfig;

