import { GameDSLConfig } from '@smallgami/engine';
import { Vector3 } from '@babylonjs/core';

export const testConfig: GameDSLConfig = {
  id: 'testConfig',
  name: 'Test Config',
  mechanism: 'dodge_and_catch',
  assets: {
    models: {
      player: '',
      alien: '',
      alien2: '',
      pinecone: '',
      // player_jump: 'bear_jump.png',
    },
    sounds: {
      ambient: {
        file: 'test_audio.mp3',
        volume: 0.1,
        loop: true,
      },
      jump: {
        file: 'jump_sound.mp3',
      },
      collision_player_box2: {
        file: 'catch_gift_sound2.wav',
      },
      collision_player_box1: {
        file: 'ouch_sound.wav',
      },
    },
    skybox: '',
    ground: '',
  },
  player: {
    description: 'a cute bear',
    size: 10,
    jumpPower: 50,
    moveSpeed: 55,
    friction: 0,
    mass: 10,
    restitution: 0.4,
    jumpAnimationDuration: 500,
    jumpSquishScale: 0.9,
    jumpStretchScale: 1.1,
    jumpOnlyOnGround: false,
    maxJumpCount: 2,
    jumpInterval: 200,
    bullets: {
      speed:  6,
      maxCount: 10,
      cooldown: 50,
      shape: {
        width: 1,
        height: 4   ,
        depth: 1,
      },
      maxDistance: 110,
      color: {
        r: 0.2,
        g: 0.8,
        b: 0.3,
      },
      opacity: 0.9,
    },
    startPosition: {
      x: 0,
      y:-30,
      z: 0,
    },
  },
  controls: {
    moveLeft: ['arrowleft'],
    moveRight: ['arrowright'],
    jump: [],
    squeezeToJump: [''],
    fireBullet: [' '],
    bulletLeft: [''],
    bulletRight: [''],
  },
  world: {
    description: 'test world environment',
    gravityMultiplier: 1,
    hasGround: true,
    ground: {
      width: 400,
      height: 10,
      depth: 400,
      posY: -35,
    },
    cameraType: 'ortho',
    cameraFovScale: 1,
    cameraTargetDelta: [0, 7, 0],
    cameraAlphaDelta: 14,
    cameraBetaDelta:0,
    cameraRadiusDelta: 0,
    HemisphericLight: {
      intensity: 1,
      color: [0.6, 0.6, 0.6],
      direction: [0, 0.4, 1],
    },
    DirectionalLight: {
      intensity: 0.1,
      color: [0.9, 0.9, 0.9],
      direction: [0, -0.85, 1],
    },
    BottomLight: {
      intensity: 0.2,
      color: [0.9, 0.9, 0.9],
      direction: [1, -0.5, 0],
    },
    skyboxType: 'sphere',
    particles: {
      maxStars: 30,
      ratioOfBlinkers: 0.65,
      size: {
        min: 0.5,
        max: 1,
      },
      colors: [[1, 1, 1, 0.3]],
      movement: {
        pattern: 'drift',
        direction: 'down',
        speed: 0.05,
        oscillation: {
          amplitude: 1,
          frequency: 0.05,
        },
      },
      blinking: {
        minInterval: 600,
        maxInterval: 800,
      },
      texture: {
        path: '/texture/star.png',
        dimensions: {
          width: 128,
          height: 128,
        },
      },
    },
    fog: {
      enabled: false,
      color: [0.4, 0.6, 0],
      start: 200,
      end: 1000,
      mode: 'linear',
    },
  },
  objects: [
    {
      name: 'alien',
      id: 'alien',
      size: new Vector3(6, 6, 6),
      onPlayerCollision: {
        player: "none",
        object: 'dispose',
      },
      onProjectileCollision: {
        object: 'dispose',
        projectile: 'dispose',
      },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(0, -2, 0),
      motionType: 1,
      physics: {
        mass: 0,
        restitution: 0.5,
        friction: 0,
      },
    },
    {
      name: 'alien2',
      id: 'alien2',
      size: new Vector3(7, 7, 7),
      onPlayerCollision: {
        player: "none",
        object: 'dispose',
      },
      onProjectileCollision: {
        object: 'dispose',
        projectile: 'dispose',
      },
      onGroundCollision: 'none',
      initialSpeed: new Vector3(0, -2, 0),
      motionType: 1,
      physics: {
        mass: 0,
        restitution: 0.5,
        friction: 0,
      },
    },
  ],
  spawn: [
    {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10, -10],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [60, 60],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
       {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10, -10],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
     {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [70, 70],
      spawnLikelihood: {
        alien: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10,-10],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [80, 80],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [20, 20],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [10, 10],
      spawnZrange: [-5, -5],
       spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [0, 0],
      spawnZrange: [-5, -5],
       spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-10,-10],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
      {
      spawnTrigger: 'once',
      spawnTriggerTime: 100,
      spawnXrange: [-20, -20],
      spawnZrange: [-5, -5],
      spawnYrange: [90, 90],
      spawnLikelihood: {
        alien2: 1,
      },
      scaleRangeX: [1, 1],
      scaleRangeY: [1, 1],
      scaleRangeZ: [1, 1],
    },
    
  ],
};

export default testConfig;

